apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zeropod-node
  namespace: zeropod-system
  labels:
    app.kubernetes.io/name: zeropod-node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zeropod-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeropod-node
    spec:
      serviceAccountName: zeropod-node
      nodeSelector:
        zeropod.ctrox.dev/node: "true"
      initContainers:
        - name: installer
          image: installer
          args: []
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/containerd
              name: containerd-etc
            - mountPath: /run/containerd
              name: containerd-run
            - mountPath: /opt/zeropod
              name: zeropod-opt
            - mountPath: /run/systemd
              name: systemd-run
            - mountPath: /etc/criu
              name: criu-etc
      containers:
        - name: manager
          image: manager
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 8080
          volumeMounts:
            - mountPath: /run/zeropod
              name: zeropod-run
      tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
      volumes:
        - name: containerd-etc
          hostPath:
            path: /etc/containerd
        - name: containerd-run
          hostPath:
            path: /run/containerd
        - name: zeropod-opt
          hostPath:
            path: /opt/zeropod
        - name: zeropod-run
          hostPath:
            path: /run/zeropod
        - name: systemd-run
          hostPath:
            path: /run/systemd
        - name: criu-etc
          hostPath:
            path: /etc/criu
