kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  InPlacePodVerticalScaling: true
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /proc
        containerPath: /host/proc
    labels:
      zeropod.ctrox.dev/node: "true"
