apiVersion: v1
kind: Namespace
metadata:
  name: zeropod-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zeropod-installer
  namespace: zeropod-system
  labels:
    app.kubernetes.io/name: zeropod-installer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zeropod-installer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeropod-installer
    spec:
      serviceAccountName: zeropod-installer
      # nodeSelector:
      # zeropod.ctrox.dev/runtime: "true"
      containers:
        - name: installer
          image: ctrox/zeropod-installer:dev
          imagePullPolicy: Never
          # securityContext:
          #   privileged: true
          volumeMounts:
            - mountPath: /etc/containerd
              name: containerd
            - mountPath: /run/containerd
              name: containerd-run
            - mountPath: /opt/zeropod
              name: zeropod-opt
            - mountPath: /run/systemd
              name: systemd
            - mountPath: /etc/criu
              name: criu-cfg
      volumes:
        - name: containerd
          hostPath:
            path: /etc/containerd
        - name: containerd-run
          hostPath:
            path: /run/containerd
        - name: zeropod-opt
          hostPath:
            path: /opt/zeropod
        - name: systemd
          hostPath:
            path: /run/systemd
        - name: criu-cfg
          hostPath:
            path: /etc/criu
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeropod-installer
  namespace: zeropod-system
---
# the installer needs to be able to install the zeropod runtimeclass
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runtimeclass-installer
rules:
  - apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
    verbs:
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: runtimeclass-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: runtimeclass-installer
subjects:
  - kind: ServiceAccount
    name: zeropod-installer
    namespace: zeropod-system
