apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  #  runtimeClassName: zeropod
  containers:
    - image: mysql
      name: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
