apiVersion: v1
kind: Pod
metadata:
  name: php
spec:
  runtimeClassName: zeropod
  containers:
    - image: wordpress
      name: wordpress
      ports:
        - containerPort: 80
      env:
        - name: WORDPRESS_DB_HOST
          value: 10.244.0.202
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: password
        - name: WORDPRESS_DB_NAME
          value: wordpress
