resources:
  - ../base
components:
  - ../in-place-scaling
images:
  - name: manager
    newName: ghcr.io/ctrox/zeropod-manager
    newTag: dev
  - name: installer
    newName: ghcr.io/ctrox/zeropod-installer
    newTag: dev
