resources:
  - ../base
images:
  - name: manager
    newName: ghcr.io/ctrox/zeropod-manager
    newTag: dev
  - name: installer
    newName: ghcr.io/ctrox/zeropod-installer
    newTag: dev
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: -in-place-scaling=true
    target:
      kind: DaemonSet
