apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    zeropod.ctrox.dev/scaledownduration: 10s
    zeropod.ctrox.dev/container-name: "nginx"
spec:
  runtimeClassName: zeropod
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
