apiVersion: v1
kind: Pod
metadata:
  name: http-echo
  labels:
    app: echo
  annotations:
    zeropod.ctrox.dev/ports-map: "container1=8080;container2=8082"
    zeropod.ctrox.dev/container-names: "container1"
    zeropod.ctrox.dev/scaledown-duration: 10s
spec:
  runtimeClassName: zeropod
  containers:
    - image: ealen/echo-server
      name: container1
      args:
        - --port=8080
      ports:
        - containerPort: 8080
    - image: ealen/echo-server
      name: container2
      args:
        - --port=8081
      ports:
        - containerPort: 8081
