apiVersion: v1
kind: Pod
metadata:
  name: wildfly-pod
  annotations:
    zeropod.ctrox.dev/ports-map: "wildfly-pod=8080"
    zeropod.ctrox.dev/container-names: wildfly-pod
    zeropod.ctrox.dev/scaledown-duration: 5m
spec:
  runtimeClassName: zeropod
  containers:
    - image: jboss/wildfly
      name: wildfly-pod
      ports:
        - containerPort: 8080
