apiVersion: v1
kind: Pod
metadata:
  name: wildfly-pod
  annotations:
    zeropod.ctrox.dev/port: "8080"
    zeropod.ctrox.dev/container-name: wildfly-pod
    zeropod.ctrox.dev/scaledownduration: 5m
spec:
  runtimeClassName: zeropod
  containers:
    - image: jboss/wildfly
      name: wildfly-pod
      ports:
        - containerPort: 8080
