name: Prepare Release

on:
  push:
    branches:
      - "release/v[012].[0-9]+.[0-9]+"

env:
  REGISTRY: ghcr.io
  INSTALLER_IMAGE_NAME: ${{ github.repository }}-installer
  MANAGER_IMAGE_NAME: ${{ github.repository }}-manager

jobs:
  update-manifests:
    name: Update Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Split branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: split
        run: echo "::set-output name=fragment::${BRANCH##*/}"

      - name: Update Deployment Image Tags
        working-directory: "config/production"
        run: |
          kustomize edit set image installer=${{ env.REGISTRY }}/${{ env.INSTALLER_IMAGE_NAME }}:${{ steps.split.outputs.fragment }}
          kustomize edit set image manager=${{ env.REGISTRY }}/${{ env.MANAGER_IMAGE_NAME }}:${{ steps.split.outputs.fragment }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update image versions"
          title: "Update image versions"
          base: main
          branch: ${{ steps.split.outputs.fragment }}
