apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zeropod-node
  namespace: zeropod-system
spec:
  template:
    spec:
      volumes:
        - name: zeropod-opt
          hostPath:
            path: /var/lib/toolbox/zeropod
