resources:
  - ../production
patchesStrategicMerge:
  - daemonset.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/args/-
        value: -host-opt-path=/var/lib/toolbox/zeropod
    target:
      kind: DaemonSet
