resources:
  - ../production
patchesStrategicMerge:
  - daemonset.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/1/args/-
        value: -opt-path=/var/lib/zeropod
    target:
      kind: DaemonSet
